### ISSUE TITLE
No proper logs or error messages when running dbt blocks in transform page

### ISSUE THREAD

**Issue by Ishankoradia** [DevDataPlatform/webapp#78]
**Describe the bug**
When you try to run any of the dbt blocks. For eg. "dbt run" and if it fails, the failure logs don't show up. Although we are able to see these logs in prefect. 

**To Reproduce**
1. Go the transform section
2. Run any the dbt block that might fail.

**Expected behavior**
If there is a failure, it should show the logs for the command

**Comment by fatchat** [comment]
Running `dbt test` for SNEHA on the staging machine fails to produce logs
- the prefect logs contain `[CRITICAL] WORKER TIMEOUT (pid:647178)` , is this related?

**Comment by fatchat** [comment]
@Ishankoradia hasn't this been resolved now?

**Comment by Ishankoradia** [comment]
@fatchat this issue is still there, was able to replicate it. I am working on resolving it.

**Comment by Ishankoradia** [comment]
This has been fixed

**Comment by nairabhishek73** [comment]
I'll need to setup sneha on staging again to check this.
